### ISSUE TITLE
Remove playerctl and jq as dependency, and support multiple players

### ISSUE THREAD

**Issue by Moon-0xff** [userbyte/XFCE-Spotify-Plugin#3]
Hello, I noticed you starred my GNOME extension a few days ago. I took a look at this project and [this script](https://github.com/Moon-0xff/mpris-scripts/blob/main/mpris-to-stdout.sh) i wrote last week could help you, as the title says, remove playerctl and jq as dependency, and support multiple players.

It's a script done in a bit of a rush but to my knowledge it does work, it only uses core utilities (and dbus-send).

**Comment by userbyte** [comment]
Thank you for the suggestion! Will definitely be using this.
